### ISSUE TITLE
Create a pdt_debug function which can be toggled on/off in the PDT Add-on preference panel 

### ISSUE THREAD

**Issue by ermo** [Clockmender/Precision-Drawing-Tools#11]
**Is your feature request related to a problem? Please describe.**
Having well judged debug prints sprinkled around in the code can be very useful during development.  However, having to comment and uncomment them before and after each release will become annoying and error prone.

**Describe the solution you'd like**
Have a `pdt_debug(msg)` function that calls `print(prefix, msg)` depending on whether a new 'print debug info' checkbox is selected in the PDT add-on preference panel.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Clockmender** [comment]
I agree this enhancement. @Ermo please implement at your convenience!

This need not delay 1.1.5-rc3.
