### ISSUE TITLE
Add isometric camera position to PDT View

### ISSUE THREAD

**Issue by ermo** [Clockmender/Precision-Drawing-Tools#15]
**Is your feature request related to a problem? Please describe.**
Sometimes it can be useful to render an isometric version of a part.  It is something which fits nicely in PDT's View functionality.

**Describe the solution you'd like**
Add two buttons linked to Operators in PDT View:
- Isometric Camera
- Reset Camera

**Describe alternatives you've considered**
None.

**Additional context**
Talked to lynxlynx in #GemRB on Freenode IRC who mentioned that being able to have an isometric camera position would also be useful when rendering sprites for use with the Baldur's Gate family of 2D isometric CRPGs.

**Comment by Clockmender** [comment]
We need simply to rotate a camera pointed at front view by 45 degrees about global Z axis then by 32.2644 degrees about global X axis. Should be easily doable, suggest we have a secondary camera set to Orthographic View to do this. camera should be named as such and should be added if not present.

Thoughts?

**Comment by ermo** [comment]
This was added to v1.1.8. Closing.
