### ISSUE TITLE
Some text labels are hardcoded in english (= not translatable)?

### ISSUE THREAD

**Issue by ermo** [Clockmender/Precision-Drawing-Tools#4]
**Describe the bug**
Some of the strings used on the labels in the PDT menus are hardcoded.

**Expected behavior**
The strings used on the labels in the PDT menus should be replaced with variables from the message strings file. This will make it easier to begin offering translations at some later point.

**Comment by Clockmender** [comment]
Fixed in https://github.com/Clockmender/Precision-Drawing-Tools/commit/f40ee6a66f7a92f441d5d575b2d882d92f303d34
