### ISSUE TITLE
Not all functions / methods in PDT have docstrings?

### ISSUE THREAD

**Issue by ermo** [Clockmender/Precision-Drawing-Tools#5]
**Describe the bug**
When reviewing the code, it appears that some of the functions do not have docstrings.  This is a technical debt that makes code maintenance more difficult.

**Expected behavior**
All functions and methods should have appropriate docstrings.

**Comment by Clockmender** [comment]
I'll put the basics in for review, ten you can comment/mamend before we commit them to the next release.

**Comment by Clockmender** [comment]
I think these are all done now.
