### ISSUE TITLE
PDT doesn't appear to install

### ISSUE THREAD

**Issue by DormantVision** [Clockmender/Precision-Drawing-Tools#7]
**Describe the bug**
PDT doesn't appear to install in either Blender 2.8, or 2.81 which was downloaded yesterday.

**To Reproduce**
1. Go to 'https://github.com/Clockmender/Precision-Drawing-Tools/tree/v.1.1.5'
2. Click on 'Download'
4. Search for but can not find PDT in the Add-ons preferences page

**Expected behavior**
I expect to be able to find and active it in Blender's Preferences Add-Ons panel

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [Vivaldi]
 - Version [2.8.1664.40]

**Smartphone (please complete the following information):**

**Additional context**
This looks to be an amazing tool, if only I could get it to install :-)

**Comment by Clockmender** [comment]
V 1.1.5 is not released yet, what you have done is to download the BitHub Repository, no the release zip file. We hope to have 1.1.5 release finalised this week.

So could I ask you to download 1.1.4 from this page:

https://github.com/Clockmender/Precision-Drawing-Tools/releases

Download the zip file, then install it from User Preferences. IT is very hard to do a manual install from a Git repository, unless you are very familiar with the processes involved.

Let me know how things go.

**Comment by DormantVision** [comment]
I've attempted to download and install in Blender 2.8 what is labelled  as "Source Code (zip)".
But am still getting the same result.

**Comment by Clockmender** [comment]
Install instructions are here:

https://github.com/Clockmender/Precision-Drawing-Tools/wiki/02-Download-&-Install

It works like this for others, I cant see wha the problem might be. Can you send a screenshot.

**Comment by DormantVision** [comment]
I have followed the installation instruction from the link that you sent, but still no joy.
Attached are screen shots of the process.

-s
![PDT install process two](https://user-images.githubusercontent.com/29440731/67513057-13290d80-f668-11e9-871f-2eafab5731e7.png)
![PDT install process one](https://user-images.githubusercontent.com/29440731/67513058-13290d80-f668-11e9-9eba-d3d6ef0958cf.png)
![PDT install process four](https://user-images.githubusercontent.com/29440731/67513059-13290d80-f668-11e9-9922-1b0c99929ba2.png)
![PDT install process three](https://user-images.githubusercontent.com/29440731/67513060-13290d80-f668-11e9-9013-a83de47214eb.png)

**Comment by Clockmender** [comment]
I think you still ahem the Repository in your Blender add-ons folder, you need to clear that out first.

**Comment by DormantVision** [comment]
I've cleared the addons folder of any previous installations.
![cleared addon folder of previous installations](https://user-images.githubusercontent.com/29440731/67513792-9303a780-f669-11e9-8067-e389c30e57ea.png)


I will make another attempt.

-s

**Comment by DormantVision** [comment]
Same result.

![PDT re-install](https://user-images.githubusercontent.com/29440731/67514086-1cb37500-f66a-11e9-9d8c-324c3ee14410.png)
![updated addon folder after re-installation](https://user-images.githubusercontent.com/29440731/67514092-1f15cf00-f66a-11e9-8511-bc7d4536b640.png)

**Comment by DormantVision** [comment]
Thanks.

**Comment by Clockmender** [comment]
Try lower case pdt in the search...

**Comment by Clockmender** [comment]
From my Mac:

![Screen Shot 2019-10-24 at 19 33 23](https://user-images.githubusercontent.com/29657804/67514726-36b67d00-f695-11e9-944c-c44c756d903b.png)

This is the latest version, but it should be the same.

**Comment by DormantVision** [comment]
lower case search gives the same result.
![lower case search](https://user-images.githubusercontent.com/29440731/67515010-d2cb8e80-f66b-11e9-8898-f8cff0047d52.png)

**Comment by Clockmender** [comment]
I am lost for an answer, I will wait until I have it tested on Windows, although I know people are running it on Windows.

Leave it with me.

**Comment by DormantVision** [comment]
One last thing.
Here are the contents of the addon folder for PDT.
![folder install contents one](https://user-images.githubusercontent.com/29440731/67515211-3950ac80-f66c-11e9-979b-3b364d5c2987.png)

![folder install contents two](https://user-images.githubusercontent.com/29440731/67515217-3c4b9d00-f66c-11e9-8d85-3a5729d992ea.png)

![folder install contents three](https://user-images.githubusercontent.com/29440731/67515224-3f468d80-f66c-11e9-85d5-089ccd4195b1.png)

**Comment by Clockmender** [comment]
I have just downloaded the file and installed it on my Mac, I will wait on for the Windows test.

**Comment by Clockmender** [comment]
OK, I can see what went wrong, you have a folder called "Precision Drawing Tools..." inside that is a folder called **clockworxpdt** yes?

So try this for me, copy the **clockworxpdt** folder to your desktop, or somewhere like that, then delete the **Precision Drawing Tools** folder, then copy the **clockworxpdt** folder back to your **addons** folder, then let me know what happens - restart Blender.

I have no idea why this happened...

**Comment by DormantVision** [comment]
It's all good now!
![looking good](https://user-images.githubusercontent.com/29440731/67517840-7d927b80-f671-11e9-8f4d-f3eac80940a2.png)

**Comment by DormantVision** [comment]
I really do appreciate you taking the time to look into this for me.

**Comment by DormantVision** [comment]
So the problem was the structure of the ZIP file?

**Comment by Clockmender** [comment]
I will check the release, seems to be.. we will look into it.

**Comment by DormantVision** [comment]
Please let me know what you find.

Thank you.

**Comment by ermo** [comment]
It turns out that Blender doesn't support Add-on names with periods `.` in them.

I've added (and successfully tested the loading of) a new release with a conformant tag and made a note that should hopefully explain what's going on.

I consider this issue resolved.

**Comment by DormantVision** [comment]
Appreciate the feedback.
Keep up the great work!
Looking forward to v1.1.5

**Comment by Clockmender** [comment]
https://github.com/Clockmender/Precision-Drawing-Tools/releases/tag/v1_1_5-rc2

This is the final release candidate.
