### ISSUE TITLE
Create a commandline cheat sheet callable from within blender (with 'help' command?)

### ISSUE THREAD

**Issue by ermo** [Clockmender/Precision-Drawing-Tools#8]
**Is your feature request related to a problem? Please describe.**
Having to keep the wiki open in a separate window to learn the command-line abbreviations is tedious.

**Describe the solution you'd like**
How about being able to write 'help' (or press a button labeled '?') in the command-line PDT widget, which will pop up a description of what the commands do, possibly with an example hidden behind a spin-button?

**Describe alternatives you've considered**
We *could* consider linking to the proper documentation for each of the commands, but that might be more time-consuming to maintain...

**Additional context**

**Comment by Clockmender** [comment]
Implemented in latest commits (various) to v.1.1.5 branch:

![Screen Shot 2019-10-30 at 10 34 52](https://user-images.githubusercontent.com/29657804/67850803-080b2d00-fb01-11e9-8284-311e346fe21d.png)

Including various revisions, following recent discussions.
